# Generated by Django 5.2.4 on 2025-08-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_portfolio', '0002_asset_alter_userprofile_account_balance_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioposition',
            unique_together=set(),
        ),
    ]
