# Generated by Django 5.2.4 on 2025-08-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_portfolio', '0003_alter_portfolioposition_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='My Portfolio', max_length=120),
        ),
    ]
